minimum_pre_commit_version: 3.7.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-sort-keys
      - id: check-yaml

  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks dir . --redact --no-banner
        language: system
        pass_filenames: false

      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        files: \.nix$

      - id: tofu-fmt
        name: tofu fmt
        entry: tofu fmt -write=true
        language: system
        files: \.(tf|tfvars)$
