datadir = "/var/lib/ethereum/erigon/sepolia"

prune.mode = "archive"

externalcl = false

http = true
"http.port" = 8454
"http.vhosts" = "*"
"http.addr" = "0.0.0.0"
"http.api" = ["eth", "erigon", "engine", "debug", "web3", "net", "trace", "txpool"]

metrics = true
"metrics.port" = 6060

nat = "stun"
