datadir = "/var/lib/ethereum/erigon/sepolia"
"ethash.dagdir" = "/var/lib/ethereum/erigon/sepolia/ethash"
nat = "stun"

chain = "sepolia"
prune.mode = "archive"

[http]
enabled = true
port = 8454
vhosts = "*"
addr = "0.0.0.0"
api = ["eth", "erigon", "engine", "debug", "web3", "net", "trace", "txpool"]

[metrics]
port = 6060
