datadir = "/var/lib/ethereum/erigon/sepolia"
cpuprofile = false
maxpeers = 100
nat = "stun"

[eth]
network = "sepolia"
prune = "archive"
cache = 4096

[rpc]
http = true
port = 8454
vhosts = "*"
addr = "0.0.0.0"
api = ["eth", "erigon", "engine", "debug", "web3", "net", "trace", "txpool"]

[metrics]
port = 6060
