datadir = "/var/lib/ethereum/erigon/sepolia"
"ethash.dagdir" = "/var/lib/ethereum/erigon/sepolia/ethash"
nat = "stun"
verbosity = "warn"
chain = "sepolia"

"prune.mode" = "archive"

"http.enabled" = true
"http.port" = 8454
"http.vhosts" = "*"
"http.addr" = "0.0.0.0"
"http.api" = ["eth", "erigon", "engine", "debug", "web3", "net", "trace", "txpool"]

"metrics.port" = 6060
