- name: Update Authorized Keys
  ansible.builtin.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  loop:
    - "{{ ssh_hsm_key }}"
    - "{{ ssh_bastion_key }}"
  when:
    - ssh_hsm_key is defined
    - ssh_bastion_key is defined
  no_log: true

- name: Ensure .config/Yubico directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/Yubico"
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ user_group }}"

- name: Write U2F key to .config/Yubico
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/Yubico/u2f_keys"
    content: "{{ u2f_key }}"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ user_group }}"
  when:
    - u2f_key is defined

- name: Ensure ~/.gnupg directory exists
  file:
    path: "/home/{{ username }}/.gnupg"
    state: directory
    mode: '0700'

- name: Add SSH support to gpg-agent.conf
  lineinfile:
    path: "/home/{{ username }}/.gnupg/gpg-agent.conf"
    line: "enable-ssh-support"
    create: yes
    mode: '0600'

- name: Enable GPG Agent
  lineinfile:
    path: "/home/{{ username }}/.gnupg/gpg.conf"
    line: "use-agent"
    create: yes
    mode: '0600'

- name: Enable SSH Control
  lineinfile:
    path: "/home/{{ username }}/.gnupg/sshcontrol"
    line: "{{ sshcontrol_key }}"
    create: yes
    mode: '0600'
