- name: Partition Disks
  ansible.builtin.include_tasks: partition.yml

- name: Mount Disks
  ansible.builtin.include_tasks: mount.yml

- name: Generate Config
  ansible.builtin.include_tasks: nixos-generate.yml

- name: Install NixOS
  become: yes
  shell: nixos-install --no-root-password
  args:
    chdir: /mnt

- name: Reboot the system
  become: yes
  shell: shutdown -r 1
  