- block:
  - name: Ensure root partition is mounted
    become: yes
    mount:
      path: /mnt
      src: /dev/disk/by-label/nixos
      fstype: ext4
      state: mounted
      fstab: /tmp/tmp.fstab

  - name: Ensure /mnt/boot directory exists
    become: yes
    file:
      path: /mnt/boot
      state: directory
      mode: '0755'

  - name: Ensure boot partition is mounted
    become: yes
    mount:
      path: /mnt/boot
      src: /dev/disk/by-label/boot
      fstype: vfat
      state: mounted
      fstab: /tmp/tmp.fstab
