- block:
  - name: Ensure root partition is mounted
    become: true
    mount:
      path: /mnt
      src: /dev/disk/by-label/NIXROOT
      fstype: ext4
      state: mounted
      fstab: /tmp/tmp.fstab

  - name: Ensure /mnt/boot directory exists
    become: true
    file:
      path: /mnt/boot
      state: directory
      mode: '0755'

  - name: Ensure boot partition is mounted
    become: true
    mount:
      path: /mnt/boot
      src: /dev/disk/by-label/NIXBOOT
      fstype: vfat
      state: mounted
      fstab: /tmp/tmp.fstab
