galaxy_info:
  author: Richard Slater
  description: Ansible role for managing SSH authorized keys and U2F keys.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: NixOS
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - u2f
    - authentication

dependencies: []
