- name: Ensure /root/secrets directory exists
  become: yes
  ansible.builtin.file:
    path: /root/secrets
    state: directory
    mode: '0700'

- name: Copy secrets.nix
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets/{{ item }}"
    dest: /root/secrets/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - secrets.nix

- name: Ensure /root/.ssh directory exists
  become: yes
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Copy SSH keys to /root/.ssh
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id/{{ item }}"
    dest: /root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: "{{ item.endswith('.pub') | ternary('0644', '0600') }}"
  loop:
    - id_ed25519
    - id_ed25519.pub

- name: Define filenames dynamically
  set_fact:
    age_secrets:
      - { name: "scetrov_password", content: "{{ user_password }}" }
      - { name: "ssh_hsm_key", content: "{{ ssh_hsm_key }}" }
      - { name: "ssh_bastion_key", content: "{{ ssh_bastion_key }}" }
      - { name: "wireless_psk", content: "WIRELESS_PSK={{ wireless_psk }}" }

- name: Gather facts about existing secret files
  local_action:
    module: find
    paths: "{{ role_path }}/files/secrets/"
    patterns: "*.age"
  register: found_secrets

- name: Set facts for existing secret files
  set_fact:
    ansible_local:
      files:
        secrets: "{{ dict(found_secrets.files | map(attribute='path') | map('basename') | zip(found_secrets.files)) }}"
  run_once: true

- name: Generate Secret Files
  local_action:
    module: shell
    cmd: "cd {{ role_path }}/files/secrets/ && echo '{{ item.content }}' | agenix -e {{ item.name }}.age"
  loop: "{{ age_secrets }}"
  run_once: true
  when: not (ansible_local['files']['secrets'][item.name + '.age'] is defined)

- name: Copy generated files to remote machine
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets/{{ item.name }}.age"
    dest: "/root/secrets/{{ item.name }}.age"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ age_secrets }}"
