- name: Ensure /root/secrets directory exists
  become: yes
  ansible.builtin.file:
    path: /root/secrets
    state: directory
    mode: '0700'

- name: Copy Nixage files to /root/secrets
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets/{{ item }}"
    dest: /root/secrets/{{ item }}
    owner: root
    group: root
    mode: '0600'
  loop:
    - secrets.nix

- name: Ensure /root/.ssh directory exists
  become: yes
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Copy SSH keys to /root/.ssh
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id/{{ item }}"
    dest: /root/.ssh/{{ item }}
    owner: root
    group: root
    mode: "{{ item.endswith('.pub') | ternary('0644', '0600') }}"
  loop:
    - id_ed25519
    - id_ed25519.pub

- name: Define filenames dynamically
  set_fact:
  nixage_secrets:
    - { name: "scetrov_password", content: "{{ user_password }}" }
    - { name: "ssh_hsm_key", content: "{{ ssh_hsm_key }}" }
    - { name: "ssh_bastion_key", content: "{{ ssh_bastion_key }}" }

- name: Generate Secret Files
  local_action:
    module: command cmd="echo '{{ item.content }}' | nixage -e /tmp/nixage-secret-{{ item.name }}.age"
  loop: "{{ nixage_secrets }}"
  run_once: true


- name: Copy generated files to remote machine
  become: yes
  ansible.builtin.copy:
    src: "/tmp/nixage-secret-{{ item.name }}.age"
    dest: "/root/secrets/{{ item.name }}.age"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ nixage_secrets }}"
