- name: Ensure /root/secrets directory exists
  become: yes
  ansible.builtin.file:
    path: /root/secrets
    state: directory
    mode: '0700'

- name: Copy Nixage files to /root/secrets
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets/{{ item }}"
    dest: /root/secrets/{{ item }}
    owner: root
    group: root
    mode: '0600'
  loop:
    - secrets.nix

- name: Ensure /root/.ssh directory exists
  become: yes
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Copy SSH keys to /root/.ssh
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id/{{ item }}"
    dest: /root/.ssh/{{ item }}
    owner: root
    group: root
    mode: "{{ item.endswith('.pub') | ternary('0644', '0600') }}"
  loop:
    - id_ed25519
    - id_ed25519.pub

- name: Generate Nixage secrets from the vault
  become: yes
  ansible.builtin.command: >
    echo "{{ item.secret }}" | agenix -e /root/secrets/{{ item.name }}.age
  args:
    creates: /root/secrets/{{ item.name }}.age
  loop:
    - { name: "scetrov_password", secret: "{{ user_password }}" }
    - { name: "ssh_hsm_key", secret: "{{ ssh_hsm_key }}" }
    - { name: "ssh_bastion_key", secret: "{{ ssh_bastion_key }}" }
  loop_control:
    label: "{{ item.name }}"
