global:
  scrape_interval: 15s

scrape_configs:
- job_name: traefik
  static_configs:
  - targets: ['traefik:8080']
- job_name: ethereum-erigon
  metrics_path: /debug/metrics/prometheus
  static_configs:
  - targets: ['erigon-ethereum-holesky:6060']
- job_name: host-node
  static_configs:
  - targets: ['host.containers.internal:9100']