global:
  scrape_interval: 15s

scrape_configs:
- job_name: traefik
  static_configs:
  - targets: ['traefik:8080']
- job_name: blocky
  static_configs:
  - targets: ['host.podman.internal:4000']
- job_name: host
  static_configs:
  - targets: ['host.podman.internal:9100']
