#!/usr/bin/env python3
"""Fixture-based tests for the generated-OIDC-secret renderer.

Covers the four behaviours required by the oidc-generated-secret-consistency
change for the Forgejo additions, plus a regression check that the pre-existing
Grafana / Dependency Track values render exactly as before:

  * first-deploy credential generation (a valid tofu output manifest renders),
  * repeated refresh (a second identical manifest is byte-stable / idempotent),
  * credential rotation (a changed secret produces a changed manifest while the
    other services stay intact),
  * invalid-input rejection (missing / empty / null / placeholder values fail
    before anything is written), and
  * Grafana + Dependency Track rendering is unchanged.

Run with either of:
  python3 -m unittest scripts.tests.test_render_generated_secrets -v
  python3 scripts/tests/test_render_generated_secrets.py
"""
from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent.parent
MODULE_PATH = SCRIPTS_DIR / "render_generated_secrets.py"
SPEC = importlib.util.spec_from_file_location("render_generated_secrets", MODULE_PATH)
assert SPEC and SPEC.loader
render_mod = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(render_mod)

RenderError = render_mod.RenderError
render = render_mod.render


def valid_outputs(**overrides):
    """A complete, valid ``tofu output -json`` shaped mapping.

    Values are non-sensitive fixture strings (no real credentials). ``overrides``
    lets a test drop/blank/mutate a single value to exercise a failure path.
    """
    base = {
        "dtrack_oidc_client_id": {"value": "0f1e2d3c4b5a697867564534231201fedcba9876", "sensitive": False},
        "dtrack_oidc_client_secret": {"value": "dtrack-secret-fixture", "sensitive": True},
        "forgejo_oidc_client_id": {"value": "aa11bb22cc33dd44ee55ff667788990011223344", "sensitive": False},
        "forgejo_oidc_client_secret": {"value": "forgejo-secret-fixture", "sensitive": True},
        "grafana_oncall_token": {"value": "oncall-token-fixture", "sensitive": True},
        "grafana_oidc_client_id": {"value": "grafana-client-id-fixture", "sensitive": False},
        "grafana_oidc_client_secret": {"value": "grafana-secret-fixture", "sensitive": True},
        "grafana_mcp_token": {"value": "mcp-token-fixture", "sensitive": True},
        "flyingfire_initial_password": {"value": "ff-pw-fixture", "sensitive": True},
        "pinkgiraffes_initial_password": {"value": "pg-pw-fixture", "sensitive": True},
    }
    base.update(overrides)
    return base


class TestFirstDeployGeneration(unittest.TestCase):
    def test_full_valid_manifest_renders(self):
        text = render(valid_outputs())
        self.assertIn("# THIS FILE IS AUTOMATICALLY GENERATED", text)
        self.assertIn('forgejo_oidc_client_id: "aa11bb22cc33dd44ee55ff667788990011223344"', text)
        self.assertIn("forgejo_oidc_client_secret:", text)
        self.assertIn("  forgejo-secret-fixture", text)

    def test_forgejo_values_present_and_distinct(self):
        text = render(valid_outputs())
        self.assertIn("forgejo-secret-fixture", text)
        self.assertNotIn('forgejo_oidc_client_secret: "forgejo-secret-fixture"', text)


class TestRepeatedRefresh(unittest.TestCase):
    def test_identical_inputs_produce_identical_output(self):
        once = render(valid_outputs())
        again = render(valid_outputs())
        self.assertEqual(once, again)


class TestRotation(unittest.TestCase):
    def test_rotated_secret_changes_only_that_value(self):
        before = render(valid_outputs())
        after = render(valid_outputs(**{
            "forgejo_oidc_client_secret": {"value": "rotated-forgejo-secret", "sensitive": True},
        }))
        self.assertNotEqual(before, after)
        self.assertIn("rotated-forgejo-secret", after)
        self.assertNotIn("forgejo-secret-fixture", after)
        # Grafana / DTrack stay intact.
        for stable in ("grafana-secret-fixture", "dtrack-secret-fixture",
                       "grafana-client-id-fixture", "0f1e2d3c4b5a697867564534231201fedcba9876"):
            self.assertIn(stable, after)


class TestInvalidInputRejection(unittest.TestCase):
    def _mutate(self, key, value):
        outs = valid_outputs()
        outs[key] = {"value": value, "sensitive": False}
        return outs

    def test_missing_key_fails(self):
        outs = valid_outputs()
        del outs["forgejo_oidc_client_id"]
        with self.assertRaises(RenderError):
            render(outs)

    def test_empty_value_fails(self):
        with self.assertRaises(RenderError):
            render(self._mutate("forgejo_oidc_client_id", ""))

    def test_whitespace_only_fails(self):
        with self.assertRaises(RenderError):
            render(self._mutate("forgejo_oidc_client_secret", "   "))

    def test_null_value_fails(self):
        with self.assertRaises(RenderError):
            render(self._mutate("forgejo_oidc_client_id", "null"))

    def test_placeholder_fails(self):
        with self.assertRaises(RenderError):
            render(self._mutate("forgejo_oidc_client_id", "forgejo_oidc_client_id_placeholder"))

    def test_grafana_missing_still_fails(self):
        outs = valid_outputs()
        del outs["grafana_oidc_client_id"]
        with self.assertRaises(RenderError):
            render(outs)


class TestPreExistingServicesUnchanged(unittest.TestCase):
    def test_grafana_and_dtrack_format_matches_legacy(self):
        text = render(valid_outputs())
        # Legacy quoted scalar form for client ids / on-call key.
        self.assertIn('dtrack_oidc_client_id: "0f1e2d3c4b5a697867564534231201fedcba9876"', text)
        self.assertIn('grafana_authentik_client_id: "grafana-client-id-fixture"', text)
        self.assertIn('grafana_oncall_api_key: "oncall-token-fixture"', text)
        # Legacy block-scalar form for secrets.
        self.assertIn("dtrack_oidc_client_secret: |", text)
        self.assertIn("grafana_authentik_client_secret: |", text)
        # The on-call key maps from the grafana_oncall_token output name.
        self.assertNotIn("grafana_oncall_token", text.splitlines()[0])
        self.assertIn("oncall-token-fixture", text)

    def test_line_order_stable(self):
        text = render(valid_outputs())
        lines = text.splitlines()
        # Generated header first, then dtrack, forgejo, grafana ordering.
        self.assertTrue(lines[0].startswith("# THIS FILE"))
        self.assertEqual(lines[2], 'dtrack_oidc_client_id: "0f1e2d3c4b5a697867564534231201fedcba9876"')


if __name__ == "__main__":
    unittest.main(verbosity=2)
