- name: Encrypt and output user passwords
  block:
    - name: Encrypt user passwords
      ansible.builtin.command: >
        echo "{{ item.password }}" | agenix -e {{ role_path }}/files/secrets/{{ item.name }}.age
      args:
        creates: {{ role_path }}/files/secrets/{{ item.name }}.age

    - name: Output generated secret filenames
      debug:
        msg: "{{ role_path }}/files/secrets/{{ item.name }}.age"
  loop:
    - { name: "scetrov_password", password: "{{ user_password }}" }
  loop_control:
    label: "{{ item.name }}"

