- name: Ensure /root/secrets directory exists
  become: yes
  ansible.builtin.file:
    path: /root/secrets
    state: directory
    mode: '0700'

- name: Copy .age files to /root/secrets
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets/{{ item }}"
    dest: /root/secrets/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - scetrov_password.age

- name: Ensure /root/.ssh directory exists
  become: yes
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Copy SSH keys to /root/.ssh
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id/{{ item }}"
    dest: /root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: "{{ item.endswith('.pub') | ternary('0644', '0600') }}"
  loop:
    - id_ed25519
    - id_ed25519.pub

- name: Generate Nixage secrets
  become: yes
  ansible.builtin.command: >
    echo "{{ item.password }}" | agenix -e /root/secrets/{{ item.name }}.age
  args:
    creates: /root/secrets/{{ item.name }}.age
  loop: "{{ lookup('file', '{{ role_path }}/files/secrets/secrets.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
