- name: Encrypt user password
  ansible.builtin.command: >
    echo "{{ user_password }}" | agenix -e {{ role_path }}/files/secrets/scetrov_password.age
  args:
    creates: {{ role_path }}/files/secrets/scetrov_password.age

- debug:
    msg:  "SECRET: {{ role_path }}/files/secrets/scetrov_password.age"