#!/usr/bin/env python3
"""Render and validate the OpenTofu-generated OIDC secret manifest.

This is the single source of truth for the shape and validation of
``src/generated-secrets.yml``. It is used by:

  * ``scripts/tofu.sh`` -- after a successful ``tofu apply`` (or when
    ``--refresh-generated-secrets`` is requested) it reads ``tofu output -json``
    on stdin and writes the plaintext manifest to the path given as the first
    CLI argument. The wrapper then encrypts that file with ansible-vault.
  * ``scripts/tests/test_render_generated_secrets.py`` -- exercises the same
    code path against non-sensitive fixtures covering first-deploy generation,
    repeated refresh, credential rotation, and invalid-input rejection, and
    asserts the pre-existing Grafana / Dependency Track behaviour is unchanged.

The rendered format is a flat YAML mapping consumed by the Ansible play
``vars_files`` (see ``src/playbook.yml``). Values are written verbatim so the
file can only ever be produced from real OpenTofu outputs; nothing in this
module hardcodes a secret.
"""
from __future__ import annotations

import argparse
import json
import sys


# Every generated-secret key we manage, in stable output order.
# Each entry is (generated_key, tofu_output_name, block_scalar) where
# block_scalar True means "the value may be multi-line and must be emitted
# as a YAML literal block". The generated key and the OpenTofu output name
# sometimes differ (historical naming) and are mapped explicitly here.
#
# Grafana and Dependency Track entries MUST remain here, unchanged, so the
# pre-existing OIDC consumers keep working (see oidc-generated-secret-consistency).
GENERATED_KEYS = [
    ("dtrack_oidc_client_id", "dtrack_oidc_client_id", False),
    ("dtrack_oidc_client_secret", "dtrack_oidc_client_secret", True),
    ("forgejo_oidc_client_id", "forgejo_oidc_client_id", False),
    ("forgejo_oidc_client_secret", "forgejo_oidc_client_secret", True),
    ("grafana_oncall_api_key", "grafana_oncall_token", False),
    ("grafana_authentik_client_id", "grafana_oidc_client_id", False),
    ("grafana_authentik_client_secret", "grafana_oidc_client_secret", True),
    ("grafana_mcp_token", "grafana_mcp_token", False),
    ("flyingfire_initial_password", "flyingfire_initial_password", False),
    ("pinkgiraffes_initial_password", "pinkgiraffes_initial_password", False),
]

HEADER = [
    "# THIS FILE IS AUTOMATICALLY GENERATED BY scripts/tofu.sh",
    "# DO NOT EDIT MANUALLY",
]


class RenderError(Exception):
    """Raised when required generated values are missing or invalid."""


def _scalar(value: object) -> str:
    text = str(value).strip()
    if text == "":
        raise RenderError("required generated value is empty")
    if text.lower() == "null":
        raise RenderError("required generated value is null")
    if text.endswith("_placeholder"):
        raise RenderError("required generated value is a placeholder")
    return text


def render(outputs: dict[str, dict]) -> str:
    """Render the manifest from a ``tofu output -json`` shaped mapping.

    ``outputs`` maps name -> ``{"value": ..., "sensitive": ...}``. All keys in
    :data:`GENERATED_KEYS` are required and validated; missing or invalid
    entries raise :class:`RenderError` before anything is returned so the
    caller can fail closed (matching the Ansible fail-fast assertions).
    """
    lines = list(HEADER)
    for generated_key, output_name, block_scalar in GENERATED_KEYS:
        if output_name not in outputs:
            raise RenderError(f"missing required tofu output: {output_name}")
        value = _scalar(outputs[output_name].get("value"))
        if block_scalar:
            # Multi-line literal block, indented two spaces (matches the
            # pre-existing Grafana/DTrack rendering consumed by vars_files).
            lines.append(f"{generated_key}: |")
            lines.extend("  " + sub for sub in value.splitlines())
        else:
            lines.append(f'{generated_key}: "{value}"')
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_path", help="path to write the manifest to")
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate stdin only and write nothing (print 'ok')",
    )
    args = parser.parse_args(argv)

    raw = sys.stdin.read()
    try:
        outputs = json.loads(raw)
        manifest = render(outputs)
    except (json.JSONDecodeError, RenderError) as exc:
        print(f"render_generated_secrets: {exc}", file=sys.stderr)
        return 1

    if args.check:
        print("ok")
        return 0

    with open(args.output_path, "w", encoding="utf-8") as handle:
        handle.write(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
