#!/usr/bin/env bash
source ~/env/grafana.env
cd terraform

SECRETS=$(ansible-vault view ../src/secrets.yml --vault-password-file ~/.ansible/nixos_vault_password)

export TF_VAR_authentik_token=$(echo "$SECRETS" | grep authentik_api_token | awk '{print $2}')
export TF_VAR_grafana_token=$GRAFANA_SERVICE_TOKEN

export PG_PASS=$(echo "$SECRETS" | grep authentik_postgresql_password | awk '{print $2}')
export PG_CONN_STR="postgres://terraform:$PG_PASS@10.229.10.2:5433/terraform_state?sslmode=disable"

tofu init -reconfigure
tofu apply

# Extract outputs and save to generated-secrets.yml using jq for safety
JSON_OUTPUTS=$(tofu output -json)

DTRACK_CLIENT_ID=$(echo "$JSON_OUTPUTS" | jq -r '.dtrack_oidc_client_id.value')
DTRACK_CLIENT_SECRET=$(echo "$JSON_OUTPUTS" | jq -r '.dtrack_oidc_client_secret.value')
GRAFANA_ONCALL_TOKEN=$(echo "$JSON_OUTPUTS" | jq -r '.grafana_oncall_token.value')
GRAFANA_CLIENT_ID=$(echo "$JSON_OUTPUTS" | jq -r '.grafana_oidc_client_id.value')
GRAFANA_CLIENT_SECRET=$(echo "$JSON_OUTPUTS" | jq -r '.grafana_oidc_client_secret.value')
GRAFANA_MCP_TOKEN=$(echo "$JSON_OUTPUTS" | jq -r '.grafana_mcp_token.value')

TMP_SEC_FILE=$(mktemp /dev/shm/generated-secrets.XXXXXX)

cat <<EOF > "$TMP_SEC_FILE"
# THIS FILE IS AUTOMATICALLY GENERATED BY scripts/tofu.sh
# DO NOT EDIT MANUALLY
dtrack_oidc_client_id: "$DTRACK_CLIENT_ID"
dtrack_oidc_client_secret: |
  $DTRACK_CLIENT_SECRET
grafana_oncall_api_key: "$GRAFANA_ONCALL_TOKEN"
grafana_authentik_client_id: "$GRAFANA_CLIENT_ID"
grafana_authentik_client_secret: |
  $GRAFANA_CLIENT_SECRET
grafana_mcp_token: "$GRAFANA_MCP_TOKEN"
EOF

ansible-vault encrypt "$TMP_SEC_FILE" --vault-password-file ~/.ansible/nixos_vault_password --output ../src/generated-secrets.yml
rm -f "$TMP_SEC_FILE"
