#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: scripts/tofu.sh [--refresh-generated-secrets] [--] [tofu args...]

Secure OpenTofu wrapper. It injects vault-backed credentials via environment
variables, runs OpenTofu, and writes encrypted generated outputs to
src/generated-secrets.yml without printing raw tokens or client secrets.

Modes:
  scripts/tofu.sh                         Run: tofu apply, then refresh generated secrets
  scripts/tofu.sh --refresh-generated-secrets
                                          Refresh src/generated-secrets.yml from current state only
  scripts/tofu.sh -- plan                 Run arbitrary tofu args, then refresh after apply only
EOF
}

REFRESH_ONLY=false
TOFU_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --refresh-generated-secrets)
            REFRESH_ONLY=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            TOFU_ARGS+=("$@")
            break
            ;;
        *)
            TOFU_ARGS+=("$1")
            shift
            ;;
    esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TERRAFORM_DIR="$ROOT_DIR/terraform"
VAULT_PASSWORD_FILE="$HOME/.ansible/nixos_vault_password"
GENERATED_SECRETS_FILE="$ROOT_DIR/src/generated-secrets.yml"

# shellcheck source=/dev/null
source "$HOME/env/grafana.env"

SECRETS="$(ansible-vault view "$ROOT_DIR/src/secrets.yml" --vault-password-file "$VAULT_PASSWORD_FILE")"

extract_secret() {
    local key="$1"
    printf '%s\n' "$SECRETS" | awk -v key="$key:" '$1 == key {print $2; exit}'
}

export TF_IN_AUTOMATION=true
export TF_VAR_authentik_token="$(extract_secret authentik_api_token)"
export TF_VAR_grafana_token="$GRAFANA_SERVICE_TOKEN"

PG_PASS="$(extract_secret authentik_postgresql_password)"
export PG_CONN_STR="postgres://terraform:${PG_PASS}@10.229.10.2:5433/terraform_state?sslmode=disable"

refresh_generated_secrets() {
    local json_outputs tmp_sec_file
    json_outputs="$(tofu -chdir="$TERRAFORM_DIR" output -json)"
    tmp_sec_file="$(mktemp /dev/shm/generated-secrets.XXXXXX)"
    chmod 0600 "$tmp_sec_file"

    jq -r '
      def required($name):
        .[$name].value
        | if . == null or . == "" then error("missing required tofu output: " + $name) else . end;
      [
        "# THIS FILE IS AUTOMATICALLY GENERATED BY scripts/tofu.sh",
        "# DO NOT EDIT MANUALLY",
        "dtrack_oidc_client_id: \"" + (required("dtrack_oidc_client_id")) + "\"",
        "dtrack_oidc_client_secret: |",
        "  " + (required("dtrack_oidc_client_secret")),
        "grafana_oncall_api_key: \"" + (required("grafana_oncall_token")) + "\"",
        "grafana_authentik_client_id: \"" + (required("grafana_oidc_client_id")) + "\"",
        "grafana_authentik_client_secret: |",
        "  " + (required("grafana_oidc_client_secret")),
        "grafana_mcp_token: \"" + (required("grafana_mcp_token")) + "\""
      ] | .[]
    ' <<< "$json_outputs" > "$tmp_sec_file"

    ansible-vault encrypt "$tmp_sec_file" \
        --vault-password-file "$VAULT_PASSWORD_FILE" \
        --output "$GENERATED_SECRETS_FILE" >/dev/null
    rm -f "$tmp_sec_file"
    echo "Refreshed encrypted generated secrets at src/generated-secrets.yml."
}

if [[ "$REFRESH_ONLY" == true ]]; then
    tofu -chdir="$TERRAFORM_DIR" init -reconfigure
    refresh_generated_secrets
    exit 0
fi

if [[ ${#TOFU_ARGS[@]} -eq 0 ]]; then
    TOFU_ARGS=(apply)
fi

tofu -chdir="$TERRAFORM_DIR" init -reconfigure
tofu -chdir="$TERRAFORM_DIR" "${TOFU_ARGS[@]}"

if [[ " ${TOFU_ARGS[*]} " == *" apply "* ]]; then
    refresh_generated_secrets
fi
