#!/bin/bash
source ~/env/grafana.env
cd terraform

SECRETS=$(ansible-vault view ../src/secrets.yml --vault-password-file ~/.ansible/nixos_vault_password)

export TF_VAR_authentik_token=$(echo "$SECRETS" | grep authentik_api_token | awk '{print $2}')
export TF_VAR_grafana_token=$GRAFANA_SERVICE_TOKEN

export PG_PASS=$(echo "$SECRETS" | grep authentik_postgresql_password | awk '{print $2}')

tofu init -reconfigure -backend-config="conn_str=postgres://terraform:$PG_PASS@10.229.10.2:5433/terraform_state?sslmode=disable"
tofu apply -auto-approve

# Extract outputs and save to generated-secrets.yml
DTRACK_CLIENT_ID=$(tofu output -raw dtrack_oidc_client_id)
DTRACK_CLIENT_SECRET=$(tofu output -raw dtrack_oidc_client_secret)
GRAFANA_ONCALL_TOKEN=$(tofu output -raw grafana_oncall_token)
GRAFANA_CLIENT_ID=$(tofu output -raw grafana_oidc_client_id)
GRAFANA_CLIENT_SECRET=$(tofu output -raw grafana_oidc_client_secret)

cat <<EOF > ../src/generated-secrets.yml
# THIS FILE IS AUTOMATICALLY GENERATED BY scripts/tofu.sh
# DO NOT EDIT MANUALLY
dtrack_oidc_client_id: "$DTRACK_CLIENT_ID"
dtrack_oidc_client_secret: "$DTRACK_CLIENT_SECRET"
grafana_oncall_api_key: "$GRAFANA_ONCALL_TOKEN"
grafana_authentik_client_id: "$GRAFANA_CLIENT_ID"
grafana_authentik_client_secret: "$GRAFANA_CLIENT_SECRET"
EOF

ansible-vault encrypt ../src/generated-secrets.yml --vault-password-file ~/.ansible/nixos_vault_password
