- name: Include Nix Channel tasks
  ansible.builtin.include_tasks: channel.yml

- name: Include NixOS sync tasks
  ansible.builtin.include_tasks: sync.yml

- name: Include NixOS rebuild tasks
  ansible.builtin.include_tasks: rebuild.yml

# - name: Include NixOS garbage collection tasks
#   ansible.builtin.include_tasks: gc.yml

- name: Include Podman Restarts
  ansible.builtin.include_tasks: podman.yml
