- name: Ensure /etc/nixos directory exists
  become: true
  file:
    path: /etc/nixos
    state: directory
    mode: '0755'

- name: Synchronize NixOS configuration to /etc/nixos
  become: true
  synchronize:
    src: "{{ role_path }}/files/etc/nixos/"
    dest: /etc/nixos/
    recursive: true
    delete: true
    rsync_opts:
      - "--exclude=*.j2"

- block:
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/blade-15-advanced-early-2020-RZ09-033.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Device
    template:
      src: "{{ role_path }}/files/device-configuration/woodford.nix.j2"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Blade 15 Advanced Model (Early 2020) - RZ09-033"

- block:
  - name: Configure 'Hyper-V Virtual Machine' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/hyperv-virtual-machine.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Hyper-V Virtual Machine' Device
    copy:
      src: "{{ role_path }}/files/device-configuration/bullit.nix"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Virtual Machine"
    - ansible_system_vendor == "Microsoft Corporation"
