- name: Ensure /etc/nixos directory exists
  become: true
  file:
    path: /etc/nixos
    state: directory
    mode: '0755'

- name: Synchronize NixOS configuration to /etc/nixos
  become: true
  synchronize:
    src: "{{ role_path }}/files/etc/nixos/"
    dest: /etc/nixos/
    recursive: true
    delete: true
    rsync_opts:
      - "--exclude=*.j2"

- name: Synchronize container configuration to /etc
  become: true
  synchronize:
    src: "{{ role_path }}/files/etc/{{ item }}/"
    dest: "/etc/{{ item }}"
    recursive: true
    delete: true
  loop:
    - ethereum
    - prometheus
    - traefik

- name: Find all .nix.j2 files
  delegate_to: localhost
  run_once: true
  find:
    paths: "{{ role_path }}/files/etc/nixos"
    patterns: "*.nix.j2"
    recurse: yes
  register: found_templates

- name: Template .nix.j2 files to /etc/nixos
  become: true
  template:
    src: "{{ item.path }}"
    dest: "/etc/nixos/{{ item.path | regex_replace('^' + role_path + '/files/etc/nixos/', '') | regex_replace('.j2$', '') }}"
  loop: "{{ found_templates.files }}"
  loop_control:
    label: "{{ item.path }}"

- block:
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/blade-15-advanced-early-2020-RZ09-033.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Device
    template:
      src: "{{ role_path }}/files/device-configuration/woodford.nix"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Blade 15 Advanced Model (Early 2020) - RZ09-033"

- block:
  - name: Configure 'Hyper-V Virtual Machine' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/hyperv-virtual-machine.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Hyper-V Virtual Machine' Device
    copy:
      src: "{{ role_path }}/files/device-configuration/bullit.nix"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Virtual Machine"
    - ansible_system_vendor == "Microsoft Corporation"

- block:
  - name: Configure 'Gigabyte BRIX BSI5' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/gb-bsi5-6200.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Gigabyte BRIX BSI5' Device
    copy:
      src: "{{ role_path }}/files/device-configuration/habiki.nix"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "GB-BSi5-6200"

- name: Set ownership and permissions /etc/nixos
  become: true
  file:
    path: "/etc/nixos"
    owner: root
    group: root
    mode: '0755'
 
- name: Find synchronized files and directories
  become: true
  find:
    paths: /etc/nixos
    recurse: yes
    file_type: file
  register: synced_files

- name: Set ownership and permissions for synchronized files
  become: true
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ synced_files.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Find synchronized files and directories
  become: true
  find:
    paths: /etc/nixos
    recurse: yes
    file_type: directory
  register: synced_dirs

- name: Set ownership and permissions for synchronized directories
  become: true
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0755'
  loop: "{{ synced_dirs.files }}"
  loop_control:
    label: "{{ item.path }}"

