- name: Ensure /etc/nixos directory exists
  become: true
  file:
    path: /etc/nixos
    state: directory
    mode: '0755'

- name: Synchronize NixOS configuration to /etc/nixos
  become: true
  synchronize:
    src: "{{ role_path }}/files/etc/nixos/"
    dest: /etc/nixos/
    recursive: true
    delete: true
    rsync_opts:
      - "--exclude=*.j2"

- name: Find all .nix.j2 files
  find:
    paths: "{{ role_path }}/files/etc/nixos"
    patterns: "*.nix.j2"
    recurse: yes
  register: found_templates

- name: Template .nix.j2 files to /etc/nixos
  become: true
  template:
    src: "{{ item.path }}"
    dest: "/etc/nixos/{{ item.path | regex_replace('^' + role_path + '/files/etc/nixos/', '') | regex_replace('.j2$', '') }}"
  loop: "{{ found_templates.files }}"
  loop_control:
    label: "{{ item.path }}"

- block:
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/blade-15-advanced-early-2020-RZ09-033.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033' Device
    template:
      src: "{{ role_path }}/files/device-configuration/woodford.nix.j2"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Blade 15 Advanced Model (Early 2020) - RZ09-033"

- block:
  - name: Configure 'Hyper-V Virtual Machine' Hardware
    copy:
      src: "{{ role_path }}/files/hardware-configuration/hyperv-virtual-machine.nix"
      dest: /etc/nixos/hardware-configuration.nix
  - name: Configure 'Hyper-V Virtual Machine' Device
    copy:
      src: "{{ role_path }}/files/device-configuration/bullit.nix"
      dest: /etc/nixos/device-configuration.nix
  when:
    - ansible_product_name == "Virtual Machine"
    - ansible_system_vendor == "Microsoft Corporation"

- name: Find synchronized files and directories
  become: true
  find:
    paths: /etc/nixos
    recurse: yes
  register: synced_items

- name: Set ownership and permissions for synchronized files
  become: true
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ synced_items.files | selectattr('isdir', 'equalto', False) | list }}"
  loop_control:
    label: "{{ item.path }}"

- name: Set ownership and permissions for synchronized directories
  become: true
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0755'
  loop: "{{ synced_items.files | selectattr('isdir', 'equalto', True) | list }}"
  loop_control:
    label: "{{ item.path }}"

