- name: Ensure /etc/nixos directory exists
  become: true
  file:
    path: /etc/nixos
    state: directory
    mode: '0755'

- name: Synchronize NixOS configuration to /etc/nixos
  become: true
  synchronize:
    src: "{{ role_path }}/files/etc/nixos/"
    dest: /etc/nixos/
    recursive: true
    delete: true

- name: Configure 'Blade 15 Advanced Model (Early 2020) - RZ09-033'
  copy:
    src: "{{ role_path }}/files/hardware-configuration/blade-15-advanced-early-2020-RZ09-033.nix"
    dest: /etc/nixos/hardware-configuration.nix
  when:
    - ansible_product_name == "Blade 15 Advanced Model (Early 2020) - RZ09-033"

- name: Configure 'Hyper-V Virtual Machine'
  copy:
    src: "{{ role_path }}/files/hardware-configuration/hyperv-virtual-machine.nix"
    dest: /etc/nixos/hardware-configuration.nix
  when:
    - ansible_product_name == "Virtual Machine"
    - ansible_system_vendor == "Microsoft Corporation"
