- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - nixos-lint

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - secrets
    - nixos
    - user-scetrov

- name: Create Bootable ISO
  hosts: woodford
  vars_files:
    - secrets
  roles:
    - nixos-live-cd
    