- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - nixos-lint

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - nixos
    - user-scetrov
    - nixos-live-cd
