- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - nixos-lint

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
    - "{{ (lookup('env', 'PWD') + '/src/generated-secrets.yml') if (lookup('env', 'PWD') + '/src/generated-secrets.yml') is file else '/dev/null' }}"
  roles:
    - secrets
    - nixos
    - role: authentik-config
      when: authentik_config_enabled | default(false)
    - user-scetrov
    - role: secrets
      tags: [ 'secrets-post' ]
