- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - role: nixos-lint
      tags: [ 'nixos', 'lint' ]

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
    - "{{ (lookup('env', 'PWD') + '/src/generated-secrets.yml') if (lookup('env', 'PWD') + '/src/generated-secrets.yml') is file else '/dev/null' }}"
  roles:
    - role: secrets
      tags: [ 'secrets', 'nixos', 'authentik', 'hermes', 'dependency-track' ]
    - role: nixos
      tags: [ 'nixos', 'hermes', 'dependency-track' ]
    - role: authentik-config
      tags: [ 'authentik', 'hermes', 'dependency-track' ]
    - role: user-scetrov
      tags: [ 'nixos', 'user' ]
    - role: dependency-track-config
      tags: [ 'dependency-track' ]
    - role: secrets
      tags: [ 'secrets-post', 'nixos', 'authentik', 'hermes', 'dependency-track' ]
