- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - nixos-lint

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - secrets
    - nixos
    - role: authentik-config
      when: authentik_config_enabled | default(false)
    - user-scetrov
