- name: Check NixOS Configuration
  hosts: localhost
  roles:
    - nixos-lint

- name: Deploy NixOS Configuration
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - secrets
    - user-scetrov
    - nixos

- name: Create Bootable ISO
  hosts: woodford
  vars_files:
    - secrets.yml
  vars:
    username: scetrov
    user_group: users
  roles:
    - nixos-live-cd
